apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
  labels:
    app: echo-server
spec:
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
        - name: echo-server
          image: quay.io/rhdevelopers/bgd:1.0.0
          env:
            - name: COLOR
              value: "blue"
          ports:
            - containerPort: 5678
